### ISSUE TITLE
Drag-and-drop snapshot tests

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1902]
Add puppeteer snapshot tests that cover the position of various drag and drop elements. There are two test flags that can be enabled to simulate a drag-and-drop. 

- `simulateDrag` - Simulates a drag in progress by rendering the blue lines that indicates where the thought will be inserted on drop (See: DropHover.tsx).
- `simulateDrop` - Renders the valid areas that a thought can be dropped as color blocks (See: DropUncle.tsx, DropChild.tsx, DropEnd.tsx).

For example, with `simulateDrop` enabled:

<img width="422" alt="image" src="https://github.com/cybersemics/em/assets/750276/e13870c6-8ffa-4636-9f5f-7d077dfbd5f3">

Test flags can be enabled in tests by setting `window.em.testFlags.simulateDrag` or `window.em.testFlags.simulateDrop` and triggering a re-render.

## Subtasks

- [x] a. Verify testFlags functionality in browser
- [x] b. Verify puppeteer snapshot tests on local machine
- [x] c. Add testHelpers method to force re-render from puppeteer test
- Create drag tests:
  - [x] d. [DragAndDropThought](https://github.com/cybersemics/em/blob/main/src/components/DragAndDropThought.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z).
  - [x] e. [DropEnd](https://github.com/cybersemics/em/blob/main/src/components/DropEnd.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z)
  - [x] f. [DropChild](https://github.com/cybersemics/em/blob/main/src/components/DropChild.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z)
  - [x] g. [DropUncle](https://github.com/cybersemics/em/blob/main/src/components/DropUncle.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z)
- Create drop tests:
  - [x] h. [DragAndDropThought](https://github.com/cybersemics/em/blob/main/src/components/DragAndDropThought.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z).
  - [x] i. [DropEnd](https://github.com/cybersemics/em/blob/main/src/components/DropEnd.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z)
  - [x] j. [DropChild](https://github.com/cybersemics/em/blob/main/src/components/DropChild.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z)
  - [x] k. [DropUncle](https://github.com/cybersemics/em/blob/main/src/components/DropUncle.tsx?rgh-link-date=2024-05-15T20%3A00%3A37Z)

**Comment by raineorshine** [comment]
Once #2038 is merged, you can continue to write snapshot tests for the existing drag-and-drop functonality.

## Drop targets

For the drop target tests, enable `em.testFlags.simulateDrop`. 

I would the following recommend tests:

1. A test that covers `DragAndDropThought` and `DropChild`

This test **does not** require a call to `dragAndDrop`, since the color blocks for `DragAndDropThought` and `DropChild` are rendered without initiating a drag.

```
- a
- b
- c
- d
```

2. A test that covers `DropEnd`

This test **does** require a call to `dragAndDrop`, since the color blocks for `DropEnd`  are only rendered once a drag has been initiated.

```
- a
  - b
    - c
```

3. A test that covers `DropUncle` (with the cursor on `c`)

This test **does not** require a call to `dragAndDrop`, since the color blocks for `DropUncle` are rendered without initiating a drag.

```
- a
  - b
    - c
      - x
    - d
  - e
```
