### ISSUE TITLE
🐼 PandaCSS

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2170]
Convert em's CSS styles to [PandaCSS](https://panda-css.com/).

## Background

**em** uses a combination of inline styles (slow, limited) and one big App.css (untyped, non-local). In 2021 there was an effort to switch to [emotion](https://github.com/emotion-js/emotion) + [twin.macro](https://github.com/ben-rogerson/twin.macro) (#1424), but it was never completed. The technology has evolved since then, and compile-time CSS-in-TS is the new best-in-class. In the lead is PandaCSS, which combines the best of many of other libraries like Stitches and Vanilla Extract. (CSS Modules is also well-liked, though I am opting for a CSS-in-TS approach for type safety and co-location.)

## Tasks

- [x] Setup PandaCSS
- [x] Convert inline styles
- [x] Convert App.css
- [x] Convert global styles to [defineGlobalStyles](https://panda-css.com/docs/concepts/writing-styles#global-styles)
- [x] Remove classNames library
- [x] Convert key frames 
- [x] Convert CSSTransition class
- [x] Convert specificity selectors
- [x] Convert classNames used for DOM behavior to aria-label or data attributes
- [x] Convert theme to [design tokens](https://panda-css.com/docs/theming/tokens)
- [x] Convert z-index variables to design tokens
- [x] Convert animation durations to design tokens
- [x] Write snapshot tests for theme
- [x] Fix theme

## Requirements

Avoid some PandaCSS-specific syntax for future compatibility:

  - Avoid [shorthand properties](https://panda-css.com/docs/concepts/writing-styles#shorthand-properties) e.g. `p`, `bg`
  - Avoid [exclamation syntax](https://panda-css.com/docs/concepts/writing-styles#important-styles) (and avoid `!important` if at all possible)
  - Avoid [pseudo properties](https://panda-css.com/docs/concepts/writing-styles#using-pseudo-props)
  - Avoid [combining shorthand properties with longhand](https://panda-css.com/docs/concepts/writing-styles#property-conflicts), e.g. `padding` and `paddingTop` together
  - Avoid [deep merging](https://panda-css.com/docs/concepts/writing-styles#merging-styles) multiple styles
  - Avoid [JSX style props](https://panda-css.com/docs/concepts/style-props)

## Commit hygiene

This conversion touches a lot of files, occurs in an active code base that changes daily, and has a high potential to break the UI when converting complex selectors. Thus, a disciplined approach with granular commits is necessary to avoid merge conflicts and make regressions easy to detect. 

- One (or more) commits per component
- One commit per className, or tightly related classNames
- One commit for complex selectors
- You are responsible for merge conflicts (PR’s are reviewed in order)
