### ISSUE TITLE
Sort thoughts setting

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#283]
Add a setting to sort thoughts within a context alphabetically. 

## Part I:
- [ ] Create toolbar button to toggle `./=sort/Alphabetical` on the `cursor` using [toggleAttribute`](https://github.com/cybersemics/em/blob/dev/src/action-creators/toggleAttribute.js).

## Part II:
When `=sort` is `Alphabetical` on a given context, which can be detected with [`attribute`](https://github.com/cybersemics/em/blob/dev/src/util/attribute.js), do the following:

- [ ] Sort the context alphabetically, ignoring rank.
- [ ] Disable re-ordering (via drag or `moveThoughtDown`/`moveThoughtUp`)
- [ ] Re-sort during editing
- [ ] Moving the cursor up and down and navigating should function as expected despite the sorting.

## Part II:
- [ ] Detect `em/Settings/Sort` to control the global sort setting. Global sort should override the default sort of "None". `=sort` on a context should override the global setting for that context. Use `=options` to define valid values of "Alphabetical" and "None". See [`INITIAL_SETTINGS`](https://github.com/cybersemics/em/blob/dev/src/constants.js#L174-L185).
