### ISSUE TITLE
Error Logging

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#598]
We will need more robust error logging to be able to catch unexpected errors encountered by real users. We also need ways to trace actions that lead up to an error or unexpected behavior. 

## Requirements
- [ ] When an error occurs, users are prompted with the option to submit the error anonymously. They should have the option to include personal information or not. 
- [ ] The last X actions should be stored so that they can be submitted with the error. 
- [ ] The user should be able to submit the last X actions at any time if they encounter unexpected behavior. 
  - Should content be included?
  - Within a few levels of depth of the cursor?
  - Within a few levels of depth of every cursor throughout the last X actions?

## Subtasks

- [ ] Research existing React logging solutions 
- [ ] List and compare most popular solutions in a few sentences. 
- [ ] Propose logging solution 
- [ ] Implement logging solution
