### ISSUE TITLE
Import from Roam Research

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#865]
## Part I
- [x] Import thoughts from Roam's JSON format (see below)
- [x] Convert to `Blocks` JSON format then use `importJSON`

## Part II
- [x] Save `create-time` as `created` property
- [x] Save `edit-time` as `lastUpdated` property
- [x] Save `create-email` as `=create-email` subthought
- [x] Save `edit-email` as `=edit-email` subthought

## Part III
- [ ] Autodetect Roam JSON in `importText`

### JSON:

```js
[
{
    "title": "September 4th, 2020",
    "children": [
    {
        "string": "A",
        "create-email": "raine@cybersemics.org",
        "create-time": 1600111381583,
        "children": [
        {
            "string": "B",
            "create-email": "raine@cybersemics.org",
            "create-time": 1600111383054,
            "children": [
            {
                "string": "C",
                "create-email": "raine@cybersemics.org",
                "create-time": 1600111383911,
                "uid": "HMN_YQtZZ",
                "edit-time": 1600111385719,
                "edit-email": "raine@cybersemics.org"
            }],
            "uid": "JBXKlMcxh",
            "edit-time": 1600111383918,
            "edit-email": "raine@cybersemics.org"
        }],
        "uid": "0VQBPmUiy",
        "edit-time": 1600111383064,
        "edit-email": "raine@cybersemics.org"
    }],
    "edit-time": 1599270696877,
    "edit-email": "raine@cybersemics.org"
},
{
    "title": "September 5th, 2020",
    "children": [
    {
        "string": "X",
        "create-email": "raine@cybersemics.org",
        "create-time": 1600111456859,
        "children": [
        {
            "string": "Y",
            "create-email": "raine@cybersemics.org",
            "create-time": 1600111457621,
            "children": [
            {
                "string": "[[September 4th, 2020]]",
                "create-email": "raine@cybersemics.org",
                "create-time": 1600111458385,
                "uid": "Wt5NR3b56",
                "edit-time": 1600111478479,
                "edit-email": "raine@cybersemics.org"
            }],
            "uid": "obXRTMWqJ",
            "edit-time": 1600111458396,
            "edit-email": "raine@cybersemics.org"
        }],
        "uid": "Pu444IoIi",
        "edit-time": 1600111457625,
        "edit-email": "raine@cybersemics.org"
    }],
    "edit-time": 1599290307051,
    "edit-email": "raine@cybersemics.org"
}
```

### Thought structure:

- September 4th, 2020
  - A
    - B
      - C
- September 5th, 2020
  - X
    - Y
      - [[September 4th, 2020]]

**Comment by anmolarora1** [comment]
@raineorshine I'm not quite sure about this part
- Save `create-email` as `=create-email` subthought
- Save `edit-email` as `=edit-email` subthought

Can you please look at the example below, and confirm if this is what we're expecting?

**JSON -** 
```
const testData = [
  {
    title: 'Fruits',
    children: [
      {
        string: 'Apple',
        'create-email': 'testemail@gmail.com',
        'create-time': 1600111381583,
        'edit-time': 1600111381580,
        uid: 'UK11200',
      },
      {
        string: 'Orange',
        'create-email': 'testemail@gmail.com',
        'create-time': 1600111383054,
        'edit-time': 1600111383050,
        uid: 'UK11233',
      }
    ],
  },
  {
    title: 'Veggies',
    children: [
      {
        string: 'Broccoli',
        'create-email': 'testemail@gmail.com',
        'create-time': 1600111381600,
        'edit-time': 1600111381599,
        uid: 'BK11200',
      },
      {
        string: 'Spinach',
        'create-email': 'testemail@gmail.com',
        'create-time': 1600111389054,
        'edit-time': 1600111389050,
        uid: 'BK11233',
      }
    ],
  }
]
```


**Thought Structure**
- Fruits
  - Apple
    - =create-email
  - Orange
    - =create-email
- Veggies
  - Broccoli
    - =create-email
  - Spinach
    - =create-email

**Comment by raineorshine** [comment]
**Thought Structure**
- Fruits
  - Apple
    - =create-email
      - testemail@gmail.com
  - Orange
    - =create-email
      - testemail@gmail.com
- Veggies
  - Broccoli
    - =create-email
      - testemail@gmail.com
  - Spinach
    - =create-email
      - testemail@gmail.com

**Comment by anmolarora1** [comment]
@raineorshine 
I'm currently working on `Autodetect Roam JSON in importText` and came across [this library](https://github.com/jquense/yup) that seems pretty useful for validating object schema/structure. Though the code for the Roam validation is pretty straightforward, this library could be potentially valuable for other use cases as well.
What are your thoughts?

**Comment by raineorshine** [comment]
Looks cool, but too heavy for our current needs. If we end up having more validation requirements we can refactor and pull it in.
